version: "3"
services:
  nginx:
    image: nginx:1.22.0-alpine
    ports: 
      - "8089:80"
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx.log/:/var/log/nginx/
      - ./app/:/var/www/html
  web:
    build: .
    volumes:
      - ./app/:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php.log:/var/log/php-fpm
  db:
    build:
      context: .
      dockerfile: DockerfileMysql
    environment:
        - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./data_volume:/var/lib/mysql