version: "3"
services:
  nginx:
    image: nginx:1.22.0-alpine
    ports: 
      - "8088:80"
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/conf.d/:/etc/nginx/conf.d/
      - ./nginx_logs/:/var/log/nginx/
      - ./app/:/var/www/html
  web:
    build: .
    volumes:
      - ./app/:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log
  db:
    build:
      context: .
      dockerfile: DockerfileMysql
    environment:
        - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./data_volume:/var/lib/mysql